es_host: 10.0.1.55
es_port: 9200
use_ssl: True
verify_certs: False
es_username: elastic
es_password: 6r0VBX5PVKW7
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl : true
from_addr: services@iinfosec.com
smtp_auth_file: /Users/efoster/git/elastalert/smtp-auth.yaml
rules_folder: rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
writeback_index: elastalert_status
alert_time_limit:
  days: 1
